set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86)

find_program(LLVM_MINGW_C_COMPILER i686-w64-mingw32-clang REQUIRED)
find_program(LLVM_MINGW_CXX_COMPILER i686-w64-mingw32-clang++ REQUIRED)
find_program(LLVM_MINGW_RC_COMPILER i686-w64-mingw32-windres REQUIRED)

set(CMAKE_C_COMPILER "${LLVM_MINGW_C_COMPILER}")
set(CMAKE_CXX_COMPILER "${LLVM_MINGW_CXX_COMPILER}")
set(CMAKE_RC_COMPILER "${LLVM_MINGW_RC_COMPILER}")

get_filename_component(LLVM_MINGW_BIN_DIR "${LLVM_MINGW_C_COMPILER}" DIRECTORY)
get_filename_component(LLVM_MINGW_ROOT "${LLVM_MINGW_BIN_DIR}" DIRECTORY)
set(CMAKE_FIND_ROOT_PATH "${LLVM_MINGW_ROOT}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
